table.insert(pfUI.gui.dropdowns.uf_bartexture, "Interface\\AddOns\\pfUI-RainbowHealthBar\\Textures\\Armory.tga:Armory") 
table.insert(pfUI.gui.dropdowns.uf_bartexture, "Interface\\AddOns\\pfUI-RainbowHealthBar\\Textures\\Cabaret 2.tga:Cabaret 2") 
table.insert(pfUI.gui.dropdowns.uf_bartexture, "Interface\\AddOns\\pfUI-RainbowHealthBar\\Textures\\ElvUI1.tga:ElvUI1") 
table.insert(pfUI.gui.dropdowns.uf_bartexture, "Interface\\AddOns\\pfUI-RainbowHealthBar\\Textures\\ElvUI2.tga:ElvUI2") 
table.insert(pfUI.gui.dropdowns.uf_bartexture, "Interface\\AddOns\\pfUI-RainbowHealthBar\\Textures\\Extra1.tga:Extra1") 
table.insert(pfUI.gui.dropdowns.uf_bartexture, "Interface\\AddOns\\pfUI-RainbowHealthBar\\Textures\\Extra2.tga:Extra2") 
table.insert(pfUI.gui.dropdowns.uf_bartexture, "Interface\\AddOns\\pfUI-RainbowHealthBar\\Textures\\Rainbow1.tga:Rainbow1") 
table.insert(pfUI.gui.dropdowns.uf_bartexture, "Interface\\AddOns\\pfUI-RainbowHealthBar\\Textures\\Rainbow2.tga:Rainbow2")
table.insert(pfUI.gui.dropdowns.uf_bartexture, "Interface\\AddOns\\pfUI-RainbowHealthBar\\Textures\\Raeli 1.tga:Raeli 1") 
table.insert(pfUI.gui.dropdowns.uf_bartexture, "Interface\\AddOns\\pfUI-RainbowHealthBar\\Textures\\Raeli 2.tga:Raeli 2") 
table.insert(pfUI.gui.dropdowns.uf_bartexture, "Interface\\AddOns\\pfUI-RainbowHealthBar\\Textures\\Raeli 3.tga:Raeli 3") 
table.insert(pfUI.gui.dropdowns.uf_bartexture, "Interface\\AddOns\\pfUI-RainbowHealthBar\\Textures\\Raeli 4.tga:Raeli 4") 
table.insert(pfUI.gui.dropdowns.uf_bartexture, "Interface\\AddOns\\pfUI-RainbowHealthBar\\Textures\\Raeli 5.tga:Raeli 5") 
table.insert(pfUI.gui.dropdowns.uf_bartexture, "Interface\\AddOns\\pfUI-RainbowHealthBar\\Textures\\Raeli 6.tga:Raeli 6") 
table.insert(pfUI.gui.dropdowns.uf_bartexture, "Interface\\AddOns\\pfUI-RainbowHealthBar\\Textures\\Simpy1.tga:Simpy1") 
table.insert(pfUI.gui.dropdowns.uf_bartexture, "Interface\\AddOns\\pfUI-RainbowHealthBar\\Textures\\Simpy2.tga:Simpy2") 
table.insert(pfUI.gui.dropdowns.uf_bartexture, "Interface\\AddOns\\pfUI-RainbowHealthBar\\Textures\\Simpy3.tga:Simpy3") 
table.insert(pfUI.gui.dropdowns.uf_bartexture, "Interface\\AddOns\\pfUI-RainbowHealthBar\\Textures\\Simpy4.tga:Simpy4") 
table.insert(pfUI.gui.dropdowns.uf_bartexture, "Interface\\AddOns\\pfUI-RainbowHealthBar\\Textures\\Simpy5.tga:Simpy5") 
table.insert(pfUI.gui.dropdowns.uf_bartexture, "Interface\\AddOns\\pfUI-RainbowHealthBar\\Textures\\Simpy6.tga:Simpy6") 
table.insert(pfUI.gui.dropdowns.uf_bartexture, "Interface\\AddOns\\pfUI-RainbowHealthBar\\Textures\\Simpy7.tga:Simpy7") 
table.insert(pfUI.gui.dropdowns.uf_bartexture, "Interface\\AddOns\\pfUI-RainbowHealthBar\\Textures\\Simpy8.tga:Simpy8") 
table.insert(pfUI.gui.dropdowns.uf_bartexture, "Interface\\AddOns\\pfUI-RainbowHealthBar\\Textures\\Simpy9.tga:Simpy9")
table.insert(pfUI.gui.dropdowns.uf_bartexture, "Interface\\AddOns\\pfUI-RainbowHealthBar\\Textures\\Simpy10.tga:Simpy10") 
table.insert(pfUI.gui.dropdowns.uf_bartexture, "Interface\\AddOns\\pfUI-RainbowHealthBar\\Textures\\Simpy11.tga:Simpy11") 
table.insert(pfUI.gui.dropdowns.uf_bartexture, "Interface\\AddOns\\pfUI-RainbowHealthBar\\Textures\\Simpy12.tga:Simpy12") 
table.insert(pfUI.gui.dropdowns.uf_bartexture, "Interface\\AddOns\\pfUI-RainbowHealthBar\\Textures\\Simpy13.tga:Simpy13") 
table.insert(pfUI.gui.dropdowns.uf_bartexture, "Interface\\AddOns\\pfUI-RainbowHealthBar\\Textures\\Simpy14.tga:Simpy14") 
table.insert(pfUI.gui.dropdowns.uf_bartexture, "Interface\\AddOns\\pfUI-RainbowHealthBar\\Textures\\Simpy15.tga:Simpy15") 
table.insert(pfUI.gui.dropdowns.uf_bartexture, "Interface\\AddOns\\pfUI-RainbowHealthBar\\Textures\\Simpy16.tga:Simpy16") 
table.insert(pfUI.gui.dropdowns.uf_bartexture, "Interface\\AddOns\\pfUI-RainbowHealthBar\\Textures\\Simpy17.tga:Simpy17") 
table.insert(pfUI.gui.dropdowns.uf_bartexture, "Interface\\AddOns\\pfUI-RainbowHealthBar\\Textures\\Simpy18.tga:Simpy18") 
table.insert(pfUI.gui.dropdowns.uf_bartexture, "Interface\\AddOns\\pfUI-RainbowHealthBar\\Textures\\Simpy19.tga:Simpy19") 
table.insert(pfUI.gui.dropdowns.uf_bartexture, "Interface\\AddOns\\pfUI-RainbowHealthBar\\Textures\\Simpy20.tga:Simpy20")  
table.insert(pfUI.gui.dropdowns.uf_bartexture, "Interface\\AddOns\\pfUI-RainbowHealthBar\\Textures\\Tukui.tga:Tukui") 